baseURL = "http://example.org/"
languageCode = "en-us"
title = "Jessica Chen"
theme = "mero"

[params]
  author = "Jessica Chen"
  description = "My awesome blog"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    title = "home"
    url = "/"
    weight = 100

  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    title = "posts"
    url = "/posts/category"
    weight = 200

  [[menu.main]]
    identifier = "Development Goals"
    name = "Development Goals"
    title = "Development Goals"
    url = "/developmentgoals/onpersonaldevelopment"
    weight = 300    

  [[menu.main]]
    identifier = "Assessments& Reflections"
    name = "Assessments& Reflectionss"
    title = "Assessments& Reflections"
    url = "/reflections/first"
    weight = 400 

[params.introduction]
   text = "**Who am I ?** 8+ years of solid digital media experience. Hands-on ability in digital marketing and CRM. Willing to take new challenges and being a pioneer to take new tasks or building a new team. Good team player, accountable, capable of multi-tasking with strong business sense, strategic thinking and driving power. Work , play and give: practiced stage performing, actively matching demand and supply for charity affairs" 

[params.social]
  [[params.social.list]]
  class = "fab"
  icon = "fa-linkedin-in"
  url = "https://www.linkedin.com/in/jessica-chen-8a5290161/"

  [[params.social.list]]
  class = "fab"
  icon = "fa-facebook"
  url = "https://www.facebook.com/sweetlan.tw"

  [[params.social.list]]
  class = "fab"
  icon = "fa-instagram"
  url = "https://www.instagram.com/sweetlan.tw/?hl=zh-tw"

 
[params.footer]
  message = "&copy; 2019 Jessica"